#!/bin/sh

uid="$(id -u)"
if [ "$uid" != "0" ]; then
  echo "su needed, please enter password."
  su -c "$0 $1"
  exit $?
fi

chroot "$NS_ROOT" $BS/bin/env -i PATH=/local/bin:/bin:$DEVEL_PREFIX/bin:$BS/bin\
    HOME=/root TERM="$TERM" PS1='\u:\w$ ' $BS/bin/sh --login
