#!/bin/sh -e

. $1
cd $( dirname $1 )
NS_DIST=${NS_DIST:-$( pwd )}

for d in $DOWNLOAD; do
  fname=$( basename "$d" )
  if [ -e "$NS_DIST/$fname" ]; then
    echo "found $fname"
  else
    mkdir -p "$NS_DIST"
    wget -O "$NS_DIST/$fname" $d
  fi
done
