#!/bin/sh -e

TMP=${TMP:-/tmp}
OUTPUT=${OUTPUT:-$TMP}

for set in bootstrap devel; do
  for dir in $set/*; do
    pkg=$( basename $dir )
    . $dir/$pkg.info
    fullname=$PRGNAME-$VERSION-$ARCH-$BUILD
    # generate recipe
    echo "#### $pkg"
    echo $set:V: $pkg
    echo install-$set:V: install-$pkg
    echo $pkg:V: $OUTPUT/$fullname.tbz
    echo $OUTPUT/$fullname.tbz:
    echo "  fetch-dist $dir/$pkg.info"
    echo "  build-pkg $dir/$pkg.build"
    echo rebuild-$pkg:V:
    echo "  fetch-dist $dir/$pkg.info"
    echo "  build-pkg $dir/$pkg.build"
    echo install-$pkg:V: $PKGLOGDIR/$fullname
    echo $PKGLOGDIR/$fullname: $OUTPUT/$fullname.tbz
    echo "  mkdir -p $PKGLOGDIR $OUTPUT"
    echo "  tar xvf $OUTPUT/$fullname.tbz -C / > $PKGLOGDIR/$fullname"
    if [ ! -z "$MAKEDEPENDS" ]; then
      echo -n $OUTPUT/$fullname.tbz:
      for dep in $MAKEDEPENDS; do
         echo -n " install-$dep"
      done
      echo
    fi
    if [ ! -z "$DEPENDS" ]; then
      echo -n install-$pkg:V:
      for dep in $DEPENDS; do
         echo -n " install-$dep"
      done
      echo
    fi

    echo
  done
done
