#!/bin/sh -e

for set in bootstrap core devel; do
  for dir in $set/*; do
    test -d $dir || continue
    pkg=$( basename $dir )
    . $dir/$pkg.info
    fullname=$PRGNAME-$VERSION-$ARCH-$BUILD
    # generate recipe
    echo "#### $pkg"
    echo $set:V: $pkg
    echo install-$set:V: install-$pkg
    echo $pkg:V: $NS_PKGDIR/$fullname.tbz
    echo $NS_PKGDIR/$fullname.tbz:
    echo "  fetch-dist $dir/$pkg.info"
    echo "  build-pkg $dir/$pkg.build"
    echo rebuild-$pkg:QV:
    echo "  fetch-dist $dir/$pkg.info"
    echo "  build-pkg $dir/$pkg.build"
    echo install-$pkg:QV: $NS_PKGDIR/$fullname.tbz
    echo "  install-pkg -pkglog $NS_PKGLOG $NS_PKGDIR/$fullname.tbz"
    echo $NS_PKGLOG/$fullname: install-$pkg
    if [ ! -z "$MAKEDEPENDS" ]; then
      echo -n $NS_PKGDIR/$fullname.tbz:
      for dep in $MAKEDEPENDS; do
         echo -n " install-$dep"
      done
      echo
    fi
    if [ ! -z "$DEPENDS" ]; then
      echo -n install-$pkg:V:
      for dep in $DEPENDS; do
         echo -n " install-$dep"
      done
      echo
    fi

    echo
  done
done
