#!/bin/sh

if [ ! "$BS" -o ! "$NS_ROOT" ]; then
  echo "BS and NS_ROOT variables are required. run . ./config"
  exit 1
fi

uid="$(id -u)"
if [ "$uid" != "0" ]; then
  printf -- "su needed. please enter password.\n"
  su -c "$0 $1"
  exit $?
fi

umount "$NS_ROOT/dev/pts"
umount "$NS_ROOT/dev/shm"
umount "$NS_ROOT/dev"
umount "$NS_ROOT/proc"
umount "$NS_ROOT/$BS"
